server:
  port: 80
  servlet:
    session:
      timeout: 30m
      cookie:
        name: JSESSIONID

logging:
  level:
    com.tca.security.web.mapper: debug

# 模板页面缓存
spring:
  thymeleaf:
    cache: false
#  aop:
#    proxy-target-class: false
  # 数据源配置
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1:3306/spring-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379


tca:
  security:
    authentication:
      loginPage: /login/page # 响应认证(登录)页面URL
      loginProcessingUrl: /login/form # 登录表单提交处理Url
      usernameParameter: username # 登录表单用户名的属性名
      passwordParameter: password # 登录表单密码的属性名
      staticPaths: # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      username: admin
      password: 123456
#      loginResponseType: JSON
      loginResponseType: REDIRECT
      ignoreUrls:
        - /login/page
        - /code/image
        - /mobile/page
        - /code/mobile
        - /mobile/form
mybatis-plus:
  type-aliases-package: com.tca.security.web.entity


