server:
  port: 80

# 模板页面缓存
spring:
  thymeleaf:
    cache: false

tca:
  security:
    authentication:
      loginPage: /login/page # 响应认证(登录)页面URL
      loginProcessingUrl: /login/form # 登录表单提交处理Url
      usernameParameter: username # 登录表单用户名的属性名
      passwordParameter: password # 登录表单密码的属性名
      staticPaths: # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      username: admin
      password: 123456
      loginResponseType: REDIRECT
      ignoreUrls:
        - /login/page
        - /code/image
